name: ice_book
description: 一个跨平台的记账应用，帮助用户管理个人财务。

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # 状态管理
  provider: ^6.1.1
  
  # 本地存储
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.2
  sqflite_common_ffi_web: ^0.4.2
  sqlite3_flutter_libs: ^0.5.20
  path: ^1.8.3
  
  # UI组件
  cupertino_icons: ^1.0.2
  flutter_slidable: ^3.0.1
  fl_chart: ^0.66.0
  
  # 日期时间
  intl: ^0.19.0
  
  # 图标
  font_awesome_flutter: ^10.6.0
  
  # 权限
  permission_handler: ^11.1.0
  
  # 文件操作
  path_provider: ^2.1.1
  
  # 网络请求
  http: ^1.1.0
  
  # 加密
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  # 使用系统默认字体，无需额外配置 