import 'package:ice_book/models/user.dart';
import 'package:ice_book/models/family_member.dart';
import 'package:ice_book/models/transaction.dart';
import 'package:ice_book/models/category.dart';
import 'package:ice_book/models/account.dart';

class SampleDataService {
  static User getSampleUser() {
    return const User(
      id: 'user_001',
      name: '张三',
      avatar: '👨',
      createdAt: null,
    );
  }

  static List<FamilyMember> getSampleFamilyMembers() {
    return [
      const FamilyMember(
        id: 'member_001',
        name: '爸爸',
        avatar: '👨',
        role: 'parent',
        isActive: true,
        createdAt: null,
        updatedAt: null,
      ),
      const FamilyMember(
        id: 'member_002',
        name: '妈妈',
        avatar: '👩',
        role: 'parent',
        isActive: true,
        createdAt: null,
        updatedAt: null,
      ),
      const FamilyMember(
        id: 'member_003',
        name: '小明',
        avatar: '👧',
        role: 'child',
        isActive: true,
        createdAt: null,
        updatedAt: null,
      ),
    ];
  }

  static List<Category> getSampleCategories() {
    return [
      const Category(
        id: 'expense_food',
        name: '餐饮',
        icon: '🍽️',
        color: '#F59E0B',
        type: 'expense',
        sortOrder: 1,
        isDefault: true,
      ),
      const Category(
        id: 'expense_transport',
        name: '交通',
        icon: '🚗',
        color: '#3B82F6',
        type: 'expense',
        sortOrder: 2,
        isDefault: true,
      ),
      const Category(
        id: 'expense_shopping',
        name: '购物',
        icon: '🛒',
        color: '#10B981',
        type: 'expense',
        sortOrder: 3,
        isDefault: true,
      ),
      const Category(
        id: 'expense_entertainment',
        name: '娱乐',
        icon: '🎮',
        color: '#8B5CF6',
        type: 'expense',
        sortOrder: 4,
        isDefault: true,
      ),
      const Category(
        id: 'expense_medical',
        name: '医疗',
        icon: '🏥',
        color: '#EF4444',
        type: 'expense',
        sortOrder: 5,
        isDefault: true,
      ),
      const Category(
        id: 'expense_education',
        name: '教育',
        icon: '📚',
        color: '#06B6D4',
        type: 'expense',
        sortOrder: 6,
        isDefault: true,
      ),
      const Category(
        id: 'expense_housing',
        name: '住房',
        icon: '🏠',
        color: '#F97316',
        type: 'expense',
        sortOrder: 7,
        isDefault: true,
      ),
      const Category(
        id: 'expense_other',
        name: '其他',
        icon: '📦',
        color: '#6B7280',
        type: 'expense',
        sortOrder: 8,
        isDefault: true,
      ),
      const Category(
        id: 'income_salary',
        name: '工资',
        icon: '💰',
        color: '#10B981',
        type: 'income',
        sortOrder: 1,
        isDefault: true,
      ),
      const Category(
        id: 'income_bonus',
        name: '奖金',
        icon: '🎁',
        color: '#F59E0B',
        type: 'income',
        sortOrder: 2,
        isDefault: true,
      ),
      const Category(
        id: 'income_investment',
        name: '投资',
        icon: '📈',
        color: '#3B82F6',
        type: 'income',
        sortOrder: 3,
        isDefault: true,
      ),
      const Category(
        id: 'income_part_time',
        name: '兼职',
        icon: '💼',
        color: '#8B5CF6',
        type: 'income',
        sortOrder: 4,
        isDefault: true,
      ),
      const Category(
        id: 'income_other',
        name: '其他',
        icon: '📦',
        color: '#6B7280',
        type: 'income',
        sortOrder: 5,
        isDefault: true,
      ),
    ];
  }

  static List<Account> getSampleAccounts() {
    return [
      const Account(
        id: 'account_001',
        userId: 'user_001',
        name: '招商银行储蓄卡',
        type: 'bank',
        bankName: '招商银行',
        balance: 8500.0,
        icon: '🏦',
        color: '#3B82F6',
        createdAt: null,
        updatedAt: null,
      ),
      const Account(
        id: 'account_002',
        userId: 'user_001',
        name: '现金',
        type: 'cash',
        bankName: '',
        balance: 1200.0,
        icon: '💰',
        color: '#10B981',
        createdAt: null,
        updatedAt: null,
      ),
      const Account(
        id: 'account_003',
        userId: 'user_001',
        name: '招商银行信用卡',
        type: 'credit',
        bankName: '招商银行',
        balance: -2320.0,
        icon: '💳',
        color: '#EF4444',
        createdAt: null,
        updatedAt: null,
      ),
      const Account(
        id: 'account_004',
        userId: 'user_001',
        name: '基金账户',
        type: 'investment',
        bankName: '',
        balance: 8000.0,
        icon: '📈',
        color: '#8B5CF6',
        createdAt: null,
        updatedAt: null,
      ),
    ];
  }

  static List<Transaction> getSampleTransactions() {
    final now = DateTime.now();
    return [
      Transaction(
        id: 'trans_001',
        userId: 'user_001',
        accountId: 'account_001',
        categoryId: 'expense_food',
        amount: 45.0,
        type: 'expense',
        note: '午餐',
        date: DateTime(now.year, now.month, now.day, 14, 30),
        budgetId: null,
        createdAt: now,
      ),
      Transaction(
        id: 'trans_002',
        userId: 'user_001',
        accountId: 'account_001',
        categoryId: 'expense_transport',
        amount: 32.0,
        type: 'expense',
        note: '打车',
        date: DateTime(now.year, now.month, now.day, 9, 15),
        budgetId: null,
        createdAt: now,
      ),
      Transaction(
        id: 'trans_003',
        userId: 'user_001',
        accountId: 'account_001',
        categoryId: 'expense_shopping',
        amount: 79.0,
        type: 'expense',
        note: '超市购物',
        date: DateTime(now.year, now.month, now.day, 18, 20),
        budgetId: null,
        createdAt: now,
      ),
      Transaction(
        id: 'trans_004',
        userId: 'user_001',
        accountId: 'account_001',
        categoryId: 'income_salary',
        amount: 500.0,
        type: 'income',
        note: '工资',
        date: DateTime(now.year, now.month, now.day - 1, 10, 0),
        budgetId: null,
        createdAt: now,
      ),
      Transaction(
        id: 'trans_005',
        userId: 'user_001',
        accountId: 'account_001',
        categoryId: 'expense_entertainment',
        amount: 120.0,
        type: 'expense',
        note: '电影票',
        date: DateTime(now.year, now.month, now.day - 2, 20, 0),
        budgetId: null,
        createdAt: now,
      ),
      Transaction(
        id: 'trans_006',
        userId: 'user_001',
        accountId: 'account_001',
        categoryId: 'expense_medical',
        amount: 85.0,
        type: 'expense',
        note: '买药',
        date: DateTime(now.year, now.month, now.day - 3, 16, 30),
        budgetId: null,
        createdAt: now,
      ),
    ];
  }
} 